In [10]:
import pandas as pd
import numpy as np

In [13]:
data = pd.read_csv("loan_dataset.csv")

In [3]:
data.head()

loan_id source       financial_institution  interest_rate  \
0  268055008619      Z  Turner, Baldwin and Rhodes          4.250   
1  672831657627      Y  Swanson, Newton and Miller          4.875   
2  742515242108      Z              Thornton-Davis          3.250   
3  601385667462      X                       OTHER          4.750   
4  273870029961      X                       OTHER          4.750   

   unpaid_principal_bal  loan_term origination_date first_payment_date  \
0                214000        360       2012-03-01            05/2012   
1                144000        360       2012-01-01            03/2012   
2                366000        180       2012-01-01            03/2012   
3                135000        360       2012-02-01            04/2012   
4                124000        360       2012-02-01            04/2012   

   loan_to_value  number_of_borrowers  ...  m4  m5 m6  m7  m8  m9  m10  m11  \
0             95                  1.0  ...   0   0  0   1   0   0    0    0   
1             72                  1.0  ...   0   0  0   0   0   0    0    1   
2             49                  1.0  ...   0   0  0   0   0   0    0    0   
3             46                  2.0  ...   0   0  0   0   0   1    1    1   
4             80                  1.0  ...   3   4  5   6   7   8    9   10   

   m12  m13  
0    0    1  
1    0    1  
2    0    1  
3    1    1  
4   11    1  

[5 rows x 29 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116058 entries, 0 to 116057
Data columns (total 29 columns):
 #   Column                    Non-Null Count   Dtype  
---  ------                    --------------   -----  
 0   loan_id                   116058 non-null  int64  
 1   source                    116058 non-null  object 
 2   financial_institution     116058 non-null  object 
 3   interest_rate             116058 non-null  float64
 4   unpaid_principal_bal      116058 non-null  int64  
 5   loan_term                 116058 non-null  int64  
 6   origination_date          116058 non-null  object 
 7   first_payment_date        116058 non-null  object 
 8   loan_to_value             116058 non-null  int64  
 9   number_of_borrowers       116058 non-null  float64
 10  debt_to_income_ratio      116058 non-null  float64
 11  borrower_credit_score     116058 non-null  float64
 12  loan_purpose              116058 non-null  object 
 13  insurance_percent         116058 non-null  f

In [14]:
data.columns

Index(['loan_id', 'source', 'financial_institution', 'interest_rate',
       'unpaid_principal_bal', 'loan_term', 'origination_date',
       'first_payment_date', 'loan_to_value', 'number_of_borrowers',
       'debt_to_income_ratio', 'borrower_credit_score', 'loan_purpose',
       'insurance_percent', 'co-borrower_credit_score', 'insurance_type', 'm1',
       'm2', 'm3', 'm4', 'm5', 'm6', 'm7', 'm8', 'm9', 'm10', 'm11', 'm12',
       'm13'],
      dtype='object')

In [15]:
req_cols= ['loan_id', 'source', 'financial_institution', 'interest_rate',
       'unpaid_principal_bal', 'loan_term', 'origination_date',
       'first_payment_date', 'loan_to_value', 'number_of_borrowers',
       'debt_to_income_ratio', 'borrower_credit_score', 'loan_purpose',
       'insurance_percent', 'co-borrower_credit_score', 'insurance_type', 'm1',
       'm2', 'm3', 'm4', 'm5', 'm6', 'm7', 'm8', 'm9', 'm10', 'm11', 'm12']

In [16]:
x = data[req_cols]

In [17]:
y = data['m13']

In [18]:
y.value_counts(normalize = True) * 100

0    99.451998
1     0.548002
Name: m13, dtype: float64

In [19]:
x = pd.get_dummies(x)

In [20]:
repay_cols = ['m1',
       'm2', 'm3', 'm4', 'm5', 'm6', 'm7', 'm8', 'm9', 'm10', 'm11', 'm12']

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train, x_test , y_train, y_test = train_test_split(x,y, test_size = 0.2,
                                                    random_state = 345, 
                                                     stratify= y )

voting classifiers

In [23]:
from collections import Counter
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from imblearn.ensemble import BalancedBaggingClassifier
import xgboost as xgb
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier

In [24]:
x_train, x_test, y_train, y_test = train_test_split(x, y,
                                                    random_state=0)

rnd_clf_1 = RandomForestClassifier()
xgb_clf_1 = xgb.XGBClassifier()

voting_clf_1 = VotingClassifier(
    estimators = [
        ('rf', rnd_clf_1), 
        ('xgb', xgb_clf_1),
    ],
    voting='soft'
)

bbc = BalancedBaggingClassifier(base_estimator=voting_clf_1, random_state=42)
bbc.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/imblearn/ensemble/_bagging.py:353: FutureWarning: `base_estimator` was renamed to `estimator` in version 0.10 and will be removed in 0.12.
  warnings.warn(


BalancedBaggingClassifier(base_estimator=VotingClassifier(estimators=[('rf',
                                                                       RandomForestClassifier()),
                                                                      ('xgb',
                                                                       XGBClassifier(base_score=None,
                                                                                     booster=None,
                                                                                     callbacks=None,
                                                                                     colsample_bylevel=None,
                                                                                     colsample_bynode=None,
                                                                                     colsample_bytree=None,
                                                                                     early_stopping_rounds=None,
                                                                                     enable_categorical=False,
                                                                                     eval_metric=None,
                                                                                     feature_types=None,
                                                                                     gamma=None,
                                                                                     gpu_id=None,
                                                                                     grow_...
                                                                                     importance_type=None,
                                                                                     interaction_constraints=None,
                                                                                     learning_rate=None,
                                                                                     max_bin=None,
                                                                                     max_cat_threshold=None,
                                                                                     max_cat_to_onehot=None,
                                                                                     max_delta_step=None,
                                                                                     max_depth=None,
                                                                                     max_leaves=None,
                                                                                     min_child_weight=None,
                                                                                     missing=nan,
                                                                                     monotone_constraints=None,
                                                                                     n_estimators=100,
                                                                                     n_jobs=None,
                                                                                     num_parallel_tree=None,
                                                                                     predictor=None,
                                                                                     random_state=None, ...))],
                                                          voting='soft'),
                          random_state=42)

In [25]:
y_pred = bbc.predict(x_test)
print(confusion_matrix(y_test, y_pred))

[[26440  2415]
 [   37   123]]


Bagging Classifier

In [26]:
from sklearn.ensemble import BaggingClassifier

In [27]:
from sklearn.tree import DecisionTreeClassifier

In [28]:
dt = DecisionTreeClassifier()

In [29]:
bg = BaggingClassifier(estimator = dt, n_estimators= 50)

In [30]:
bg.fit(x_train, y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=50)

In [31]:
confusion_matrix(y_test, y_pred)

array([[26440,  2415],
       [   37,   123]])

In [5]:
from sklearn.ensemble import RandomForestClassifier

Random Forest Classifier

In [32]:
rf_classifier = RandomForestClassifier()
rf_classifier.fit(x_train,y_train)

RandomForestClassifier()

In [35]:
confusion_matrix(y_test, y_pred)

array([[26440,  2415],
       [   37,   123]])